### ISSUE TITLE
Today: zsh:1: no such file or directory: /Users/?/.wakatime/wakatime-cli-darwin-arm64

### ISSUE THREAD

**Issue by GopherJ** [wakatime/vim-wakatime#109]
hi, it seems that mac m1 is not supported

**Comment by GopherJ** [comment]
hi, it seems that mac m1 is not supported

**Comment by chicopaec** [comment]
I also hit the same issue yesterday from nowhere. `~/.wakatime` doesn't exists since before. Created it and put `wakatime-cli-linux-amd64` there (from https://github.com/wakatime/wakatime-cli/releases/tag/v1.28.3), then I got the following error:

```
Traceback (most recent call last):
  File "/home/chicopaec/.local/share/nvim/plugged/vim-wakatime/scripts/install_cli.py", line 127, in parseConfigFile
    configs.readfp(fh)
  File "/usr/lib/python3.9/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.9/configparser.py", line 1096, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/home/chicopaec/.wakatime.cfg' [line 10]: option 'api_key' in section 'settings' already exists
```

Checking `~/.wakatime.cfg` (which seems misplaced, isn't it supposed to be inside the `~/.wakatime` directory?), the `api_key` key is appearing many times. Deleting all the entries but one makes things work again.

Thing is, the error didn't start appearing until after a week of no data I started noticing that there was no data, and the error didn't appear until I enabled debug mode and saw the same error as @GopherJ put above.

Someone seems to have majorly fucked up a migration or deploy of a new version of Wakatime, and unfortunately things seems mismanaged enough that I now have to cancel my subscription and find a different service that works reliably, or at least tells me when it doesn't work.

**Comment by chicopaec** [comment]
@alanhamlett @wakatime what's with the deleted comment? Looks rather unsightly to see a comment deleted from the reporter without any information about why it was deleted.

**Comment by alanhamlett** [comment]
@chicopaec I moved his comment into the issue description, which was empty previously.

**Comment by alanhamlett** [comment]
@chicopaec yours looks like a separate issue to this one. What happened there is we started using Python for installing & updating wakatime-cli. Python's INI config parser by default doesn't like duplicate keys, and your `~/.wakatime.cfg` must have contained duplicate keys before but it was ignored until we rolled out the Python `install_cli.py` script.

I've fixed your issue with 31834fe5bdc220d3677eeb42fafffdead8fc6926, but will leave this open because there might be a separate issue not related to duplicate keys.

**Comment by GopherJ** [comment]
I also recreated `~/.wakatime/wakatime-cli-darwin-arm64`

**Comment by alanhamlett** [comment]
That's the problem.. there is an arm64 release. The plugin just isn't downloading `~/.wakatime/wakatime-cli-darwin-arm64` from GitHub correctly.

If you add `debug = true` to your `~/.wakatime.cfg` file then run `vim-wakatime/scripts/install_cli.py` what output do you see? If it says "up to date" or "304", try deleting `~/.wakatime/wakatime-cli-darwin-arm64` then run `install_cli.py` again to simulate the original bug.

**Comment by bausmeier** [comment]
@alanhamlett I'm experiencing the same issue and following your instructions above this is the output I get:

```
[WakaTime] Downloading wakatime-cli...
[WakaTime] GitHub API Response 304
[WakaTime] Downloading wakatime-cli from https://github.com/wakatime/wakatime-cli/releases/download/v1.30.0/wakatime-cli-linux-amd64.zip
[WakaTime] Traceback (most recent call last):
  File "vim-wakatime/scripts/install_cli.py", line 194, in downloadCLI
    download(url, zip_file)
  File "vim-wakatime/scripts/install_cli.py", line 454, in download
    urlretrieve(url, filePath)
  File "/usr/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

It seems to be trying to download the assets from the `v1.30.0` release which doesn't exist.

The script also keeps deleting the binary if I put it in place manually.

I have the latest commit (02405f1b4077a0bcc99b8111de967582f45ec776) checked out.

**Comment by bausmeier** [comment]
I managed to fix the issue by setting `cli_version` to an older version (`v1.28.6`), and `cli_version_last_modified` to an earlier date in `~/.wakatime-internal.cfg`. Not sure how the value of `v1.30.0` got in there in the first place since I've never modified that file manually, but at least it's working now :+1:

**Comment by alanhamlett** [comment]
@gandarez I think we deleted that release right? Let's do a release to fix this, since GitHub is still reporting 1.30.0 as the latest even thought it's not available.

**Comment by alanhamlett** [comment]
@bausmeier that's a different issue, I've created a new issue for it here: wakatime/wakatime-cli#594

**Comment by alanhamlett** [comment]
Closing this issue, because it might have been a temporary network issue when downloading `wakatime-cli-darwin-arm64`.
