### ISSUE TITLE
Error on Load: Windows in Powershell using Neovim can't find wakatime-cli.exe

### ISSUE THREAD

**Issue by ChrisTitusTech** [wakatime/vim-wakatime#147]
**Expected behavior (what should have happened)**:
wakatime nvim doesn't load as it is looking for `wakatime-cli.exe` when the win32 exe is `wakatime-cli-windows-amd64.exe`

**Environment**:

- OS: Windows 11 21H2
- Platform: amd64

**Comment by Yakiyo** [comment]
same issue for me. getting error wakatime-cli.exe is not an executable

**Comment by alanhamlett** [comment]
The install script should already create a symlink from `~/.wakatime/wakatime-cli.exe` to `~/.wakatime/wakatime-cli-windows-amd64.exe`:
https://github.com/wakatime/vim-wakatime/blob/4692ec3e77ade9e65171182296cca74352a39a12/scripts/install_cli.py#L505

**Comment by Asthestarsfalll** [comment]
Hi, any solutions?

**Comment by alanhamlett** [comment]
Should be fixed now on master branch at 2c7770ad1d62833fb8350ac1a8f1f870e29254cb. Please update your vim-wakatime plugin then restart NeoVim and let me know if it works.

**Comment by ParadiseWitch** [comment]
Now I have the same issue, but I have "wakatime-cli-windows-386.exe" instead of "wakatime-cli-windows-amd64.exe".
Like this:
![image](https://github.com/wakatime/vim-wakatime/assets/37146904/48cd43b6-3534-44aa-932c-f938162e76c5)

If i rename the "wakatime-cli-windows-386.exe" file to "wakatime-cli.exe", when i restart nvim, it will be removed.
