### ISSUE TITLE
Where to enter the API-key?

### ISSUE THREAD

**Issue by dj-hedgehog** [wakatime/vim-wakatime#36]
I'm never asked to enter the API-key (VIM 7.3 on OS X).

This is my `~/.vimrc` so **what am I doing wrong?**

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'wakatime/vim-wakatime'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
```

**Comment by alanhamlett** [comment]
Did you type `:BundleInstall` inside vim?

Also, the plugins share a config file in your home directory so if you have other plugins installed they won't ask for your api key twice.

**Comment by dj-hedgehog** [comment]
What is the name of the config file?

This is the result of `:BundleInstall`.

![vim 2015-12-28 13-47-16](https://cloud.githubusercontent.com/assets/7140800/12018897/876553da-ad69-11e5-8fd6-c5922d8a67cd.png)

**Comment by alanhamlett** [comment]
`.wakatime.cfg`

That output above means you already had vim-wakatime installed. Do you also have a `.wakatime.cfg` file with your api key?

**Comment by dj-hedgehog** [comment]
@alanhamlett 
Yeah there is such a file.
Could it be created by Atom or Visual Studio Code?

**Comment by alanhamlett** [comment]
Visual Studio Code uses the common config file (`.wakatime.cfg`). If you see Vim at the top of this list after editing some files in Vim, then everything is working:

https://wakatime.com/api/v1/users/current/user_agents

Sublime Text and Atom use their own config files (because of editor conventions). All other plugins use the common `.wakatime.cfg` config file.

**Comment by dj-hedgehog** [comment]
Yup, Vim is tracked as well. Thanks a lot :)

**Comment by Akhil-Sharma-26** [comment]
You can also use `:WakaTimeApiKey` command in vim to change the api key or enter for the first time. If due to some reason, your `.wakatime.cfg` has not been created, then the above command will help you create it. Then you can edit that file and directly paste in your api key into it.
<br>
Its Content is someWhat like this:
`[settings] \n
api_key=Your_API_KEY  \n
status_bar_enabled = true`
