### ISSUE TITLE
Path contains `static` causes errors

### ISSUE THREAD

**Issue by vincentzhezhang** [wakatime/vim-wakatime#50]
Environments:
- Ubuntu 14.04 LTS
- NeoVim v0.2.0

Steps to replicate:
```
mkdir static
cd static
touch test.md
nvim test.md
```
and you will see this error:
![waka](https://cloud.githubusercontent.com/assets/1330120/26097203/550d2900-3a56-11e7-932e-9c99be4b1d74.png)

**Comment by alanhamlett** [comment]
Unable to reproduce this issue.

Tested on with Ubuntu 16.04 and NeoVim 0.1.7.

**Comment by vincentzhezhang** [comment]
After some digging with isolated vim config, the root cause is this line in my vim config:
`set wildignore+=*/static/*`
which somehow makes `vim-wakatime` cannot find the file.
It is still weird though why the error message saying

>  E482: Can't open file /.wakatime.cfg for writing: permission denied

which is a bit misleading

**Comment by alanhamlett** [comment]
Thanks for figuring it out, you can add that back to your vimrc after updating the vim-wakatime plugin since it's been fixed now.

When a `wildcard` pattern matches the folder Vim/NeoVim is opened from it causes `expand('~')` to return empty string instead of your home directory. Setting `&wildcard` to empty string temporarily while loading the plugin fixed it.

**Comment by vincentzhezhang** [comment]
Thanks for the nice explanation, the fix work like a charm!
