### ISSUE TITLE
vim offline doesn't work

### ISSUE THREAD

**Issue by hafah** [wakatime/vim-wakatime#70]
vim 8.0.1655
waketime 7.1.1

I work in vim and everything works fine eventhough waketime says I've worked till 8:50 when It's 9:00. So I have to work an extra 10 minutes to see the number increase on the website.

Offline waketime doesn't do anything.

**Comment by hafah** [comment]
I use WSL (ubuntu under windows).
I use bash 4.3.48
and tmux 2.1

**Comment by alanhamlett** [comment]
Can you run `:WakaTimeDebugEnable` command in Vim then tail `~/.wakatime.log` file while editing a file in Vim when offline and online? You can force an event in `~/.wakatime.log` by saving a file in Vim, so for ex: save a file in Vim without internet and you should see a line printed to `~/.wakatime.log` with a non-200 response code, then turn on your networking and save the file in Vim again and you should see two heartbeats sent to the api along with two id's in the results data array.

That above is if everything is working, otherwise you should see an error message printed instead.

**Comment by hafah** [comment]
I changed laptop and it works now. So eventhough I don't know what it is. I do remember vaguely some file was too big. 

But this issue can be closed.
