### ISSUE TITLE
Error detected while processing function <SNR>86_NeovimAsyncExitHandler:

### ISSUE THREAD

**Issue by jfernandz** [wakatime/vim-wakatime#84]
I'm getting this error with debug enabled, and the stats are not being sent, what's wrong in the system? 

```
Error detected while processing function <SNR>86_NeovimAsyncExitHandler:                                                                                                  
line    6:                                                                                                                                                                
[WakaTime] Error 105: Traceback (most recent call last):^@  
File "/home/wyre/.vim_runtime/my_plugins/vim-wakatime/packages/wakatime/main.py", line 54, in execute^@    hb = Heartbeat(vars(args), args, configs)^@  
File "/home/wyre/.vim_runtime/my_plugins/vim-wakatime/packages/wakatime/heartbeat.py", line 124, in __init__^@    local_file=args.local_file)^@  
File "/home/wyre/.vim_runtime/my_plugins/vim-wakatime/packages/wakatime/stats.py", line 57, in get_file_stats^@    lexer = get_lexer(language)^@  
File "/home/wyre/.vim_runtime/my_plugins/vim-wakatime/packages/wakatime/stats.py", line 254, in get_lexer^@    lexer_cls = find_lexer_class(language)^@  
File "/home/wyre/.vim_runtime/my_plugins/vim-wakatime/packages/wakatime/packages/pygments/lexers/__init__.py", line 70, in find_lexer_class^@    for cls in find_plugin_lexers():^@  
File "/home/wyre/.vim_runtime/my_plugins/vim-wakatime/packages/wakatime/packages/pygments/plugin.py", line 53, in find_plugin_lexers^@    yield entrypoint.load()^@  
File "/home/wyre/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in load^@    self.require(*args, **kwargs)^@  
File "/home/wyre/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in require^@    items = working_set.resolve(reqs, env, installer, extras=self.extras)^@  
File "/home/wyre/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve^@    raise VersionConflict(dist, req).with_context(dependent_req)^@pkg_resources.ContextualVersionConflict: (parso 0.4.0 (/home/wyre/.local/lib/python3.7/site-packages), Requirement.parse('parso>=0.5.0'), {'jedi'})^@^@                                                              
Press ENTER or type command to continue

```

I'm pretty sure is my bad, but I cannot find what is wrong

**Comment by alanhamlett** [comment]
The error happens when pygments (used by wakatime for language detection) tries to import a lexer:
`pkg_resources.ContextualVersionConflict: (parso 0.4.0 (/home/wyre/.local/lib/python3.7/site-packages), Requirement.parse('parso>=0.5.0'), {'jedi'})`

If you run this command does it help?
`pip uninstall jedi`

Or `pip uninstall parso`

**Comment by technbuzz** [comment]
I am getting the same error on **NVIM for windows**, I used plug to install the package. I tried removing the package folder, reinstalling but nothing helps. Looks like a long awaiting issue.

**Comment by technbuzz** [comment]
> I am getting the same error on **NVIM for windows**, I used plug to install the package. I tried removing the package folder, reinstalling but nothing helps. Looks like a long awaiting issue.

My bad, wakatime couldn't find python, the **python path** in environment variable was messed up. Using the `WakaTimeApiKey` command in vim saved me. I think the error can be made more descriptive. Or may Plugin manager could report somehow

**Comment by GopherJ** [comment]
same error here

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/129706738-d499a781-4c89-4857-af02-ca4c197fa70b.png)

**Comment by GopherJ** [comment]
any ideas?

**Comment by hash-bang** [comment]
@alanhamlett, hmm... yes you are right debug is enabled for some reason in `~/.wakatime.cfg`. I don't recall turning this on so I assume this is the default after going through the initial setup wizard?

I'll let it run with this disabled for a while and see if the error reoccurs.

**Comment by alanhamlett** [comment]
> I assume this is the default after going through the initial setup wizard?

Nope, default is debug off.

**Comment by vectorcr** [comment]
I am running pop_os and I am running into this issue as well. Logs below. 

`{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on 127.0.0.53:53: server misbehaving","now":"2021-09-05T02:03:16-06:00","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-05T02:03:17-06:00","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-05T02:03:18-06:00","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:76","func":"SendHeartbeats","level":"warning","message":"file 'extension-output-vscode.git-#1' does not exist. ignoring this heartbeat","now":"2021-09-07T05:04:35-06:00","version":"v1.24.1"}
{"now": "2021/09/07 19:39:10 -0600", "version": "13.1.0", "plugin": "bash-wakatime/1.0.0", "time": 1631065150.1007152, "caller": "/home/lorenzo/.local/lib/python3.9/site-packages/wakatime/api.py", "lineno": 56, "is_write": true, "file": "nvim", "level": "DEBUG", "message": "Sending heartbeats to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk"}
{"now": "2021/09/07 19:39:10 -0600", "version": "13.1.0", "plugin": "bash-wakatime/1.0.0", "time": 1631065150.1007152, "caller": "/home/lorenzo/.local/lib/python3.9/site-packages/wakatime/api.py", "lineno": 62, "is_write": true, "file": "nvim", "level": "DEBUG", "message": "[{'time': 1631065150.1007152, 'entity': 'nvim', 'type': 'app', 'category': None, 'is_write': True, 'project': 'Terminal', 'branch': None, 'language': None, 'dependencies': [], 'lines': None, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.1.0 (Linux-5.13.0-14.1-liquorix-amd64-x86_64-with-glibc2.33) Python3.9.5.final.0 bash-wakatime/1.0.0'}]"}
{"now": "2021/09/07 19:39:11 -0600", "version": "13.1.0", "plugin": "bash-wakatime/1.0.0", "time": 1631065150.1007152, "caller": "/home/lorenzo/.local/lib/python3.9/site-packages/wakatime/api.py", "lineno": 289, "is_write": true, "file": "nvim", "level": "DEBUG", "message": "{'response_code': 202, 'results': [[{'data': {'id': '94c738ac-6a32-41cc-80e9-2bd4a4598363'}}, 201]]}"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:58","func":"Run","level":"debug","message":"command: version","now":"2021-09-07T19:39:28-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:88","func":"Run","level":"debug","message":"command: heartbeat","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:80","func":"SendHeartbeats","level":"debug","message":"heartbeat params: category: 'coding', cursor position: '', entity: '/home/lorenzo/git/vectorcr.com/src/components/vnav.js', entity type: 'file', num extra heartbeats: 0, is write: false, language: '', line number: '', lines in file: '', offline disabled: false, offline queue file: '', offline sync max: 1000, time: 1631065175.46434, api params: (api key: 'a22c...', api url: 'https://api.wakatime.com/api/v1', backoff at: '', backoff retries: 0, hostname: 'griever-0', plugin: 'vscode/1.60.0 vscode-wakatime/17.0.0', timeout: 2m0s, disable ssl verify: false, proxy url: '', ssl cert filepath: ''), filter params: (exclude: '[]', exclude unknown project: false, include: '[]', include only with project file: false), project params: (alternate: 'vectorcr.com', disable submodule: '[]', map patterns: '[]', override: ''), sanitize params: (hide branch names: '[]', hide file names: '[]', hide project names: '[]')","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/filter/filter.go:28","func":"1","level":"debug","message":"execute heartbeat filtering","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/entity_modify.go:15","func":"1","level":"debug","message":"execute heartbeat entity modifier","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/filestats/filestats.go:28","func":"1","level":"debug","message":"execute filestats detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/language/language.go:20","func":"1","level":"debug","message":"execute language detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/deps/deps.go:38","func":"1","level":"debug","message":"execute dependency detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/project.go:60","func":"1","level":"debug","message":"execute project detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/file.go:23","func":"Detect","level":"debug","message":"execute file project detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/map.go:30","func":"Detect","level":"debug","message":"execute map project detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/git.go:25","func":"Detect","level":"debug","message":"execute git project detection","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/sanitize.go:27","func":"1","level":"debug","message":"execute heartbeat sanitization","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:67","func":"1","level":"debug","message":"execute offline queue with file /home/lorenzo/.wakatime.bdb","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/backoff/backoff.go:41","func":"1","level":"debug","message":"execute heartbeat backoff algorithm","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/api/heartbeat.go:26","func":"SendHeartbeats","level":"debug","message":"sending 1 heartbeat(s) to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/api/heartbeat.go:33","func":"SendHeartbeats","level":"debug","message":"heartbeats: [{\"branch\":\"dev\",\"category\":\"coding\",\"cursorpos\":null,\"dependencies\":[\"react\"],\"entity\":\"/home/lorenzo/git/vectorcr.com/src/components/vnav.js\",\"type\":\"file\",\"is_write\":null,\"language\":\"JavaScript\",\"lineno\":null,\"lines\":27,\"project\":\"vectorcr.com\",\"time\":1631065175.464345,\"user_agent\":\"wakatime/v1.24.1 (linux-5.13.0-14.1-liquorix-amd64-x86_64) go1.17 vscode/1.60.0 vscode-wakatime/17.0.0\"}]","now":"2021-09-07T19:39:35-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:59","func":"Run","level":"debug","message":"successfully sent heartbeat(s)","now":"2021-09-07T19:39:36-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:103","func":"func1","level":"debug","message":"execute offline sync with file /home/lorenzo/.wakatime.bdb","now":"2021-09-07T19:39:36-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:130","func":"func1","level":"debug","message":"no queued heartbeats ready for sending","now":"2021-09-07T19:39:36-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/offlinesync/offlinesync.go:59","func":"Run","level":"debug","message":"successfully synced offline activity","now":"2021-09-07T19:39:36-06:00","version":"v1.24.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:76","func":"Run","level":"debug","message":"command: today","now":"2021-09-07T19:39:40-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/today/today.go:51","func":"Run","level":"debug","message":"successfully fetched today for status bar","now":"2021-09-07T19:39:41-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:88","func":"Run","level":"debug","message":"command: heartbeat","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:88","func":"SendHeartbeats","level":"debug","message":"heartbeat params: category: 'coding', cursor position: '', entity: '/home/lorenzo/git/vectorcr.com/src/components/vnav.js', entity type: 'file', num extra heartbeats: 0, is write: true, language: '', line number: '', lines in file: '', offline disabled: false, offline queue file: '', offline sync max: 1000, time: 1631065186.72944, api params: (api key: 'a22c...', api url: 'https://api.wakatime.com/api/v1', backoff at: '', backoff retries: 0, hostname: 'griever-0', plugin: 'vscode/1.60.0 vscode-wakatime/17.0.0', timeout: 2m0s, disable ssl verify: false, proxy url: '', ssl cert filepath: ''), filter params: (exclude: '[]', exclude unknown project: false, include: '[]', include only with project file: false), project params: (alternate: 'vectorcr.com', disable submodule: '[]', map patterns: '[]', override: ''), sanitize params: (hide branch names: '[]', hide file names: '[]', hide project names: '[]')","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/filter/filter.go:28","func":"1","level":"debug","message":"execute heartbeat filtering","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/entity_modify.go:15","func":"1","level":"debug","message":"execute heartbeat entity modifier","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/filestats/filestats.go:28","func":"1","level":"debug","message":"execute filestats detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/language/language.go:20","func":"1","level":"debug","message":"execute language detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/deps/deps.go:38","func":"1","level":"debug","message":"execute dependency detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/project.go:60","func":"1","level":"debug","message":"execute project detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/file.go:23","func":"Detect","level":"debug","message":"execute file project detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/map.go:30","func":"Detect","level":"debug","message":"execute map project detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/project/git.go:25","func":"Detect","level":"debug","message":"execute git project detection","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/heartbeat/sanitize.go:27","func":"1","level":"debug","message":"execute heartbeat sanitization","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:67","func":"1","level":"debug","message":"execute offline queue with file /home/lorenzo/.wakatime.bdb","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/backoff/backoff.go:41","func":"1","level":"debug","message":"execute heartbeat backoff algorithm","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/api/heartbeat.go:26","func":"SendHeartbeats","level":"debug","message":"sending 1 heartbeat(s) to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/api/heartbeat.go:33","func":"SendHeartbeats","level":"debug","message":"heartbeats: [{\"branch\":\"dev\",\"category\":\"coding\",\"cursorpos\":null,\"dependencies\":[\"react\"],\"entity\":\"/home/lorenzo/git/vectorcr.com/src/components/vnav.js\",\"type\":\"file\",\"is_write\":true,\"language\":\"JavaScript\",\"lineno\":null,\"lines\":27,\"project\":\"vectorcr.com\",\"time\":1631065186.7294366,\"user_agent\":\"wakatime/v1.26.0 (linux-5.13.0-14.1-liquorix-amd64-x86_64) go1.17 vscode/1.60.0 vscode-wakatime/17.0.0\"}]","now":"2021-09-07T19:39:46-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:67","func":"Run","level":"debug","message":"successfully sent heartbeat(s)","now":"2021-09-07T19:39:47-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:103","func":"func1","level":"debug","message":"execute offline sync with file /home/lorenzo/.wakatime.bdb","now":"2021-09-07T19:39:47-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:130","func":"func1","level":"debug","message":"no queued heartbeats ready for sending","now":"2021-09-07T19:39:47-06:00","version":"v1.26.0"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/offlinesync/offlinesync.go:59","func":"Run","level":"debug","message":"successfully synced offline activity","now":"2021-09-07T19:39:47-06:00","version":"v1.26.0"}`

**Comment by vectorcr** [comment]
> I am running pop_os and I am running into this issue as well. Logs below.
> 
> `{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/pkg/offline/offline.go:130","func":"func1","level":"debug","message":"no queued heartbeats ready for sending","now":"2021-09-07T19:39:47-06:00","version":"v1.26.0"} {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/offlinesync/offlinesync.go:59","func":"Run","level":"debug","message":"successfully synced offline activity","now":"2021-09-07T19:39:47-06:00","version":"v1.26.0"}`

I ran the `pip uninstall jedi parso` and I don't have either installed. In the meantime I am going to fallback to vscode which doesn't seem to be showing the same issues. Hopefully this can be fixed soon :)

**Comment by alanhamlett** [comment]
Fixed with 5ef2cc4c68af5d291ba85dc444ebb1b26158444c. Please update your vim-wakatime plugin to get the fix.

**Comment by danzt** [comment]
help me please!
`Today: Traceback (most recent call last):                                                              
  File "/home/danzt/.vim/plugged/vim-wakatime/packages/wakatime/configs.py", line 58, in parseConfigFile
    configs.read_file(fh)
  File "/home/danzt/.vim/plugged/vim-wakatime/packages/wakatime/packages/configparser/__init__.py", line 724, in
 read_file
    self._read(f, source)
  File "/home/danzt/.vim/plugged/vim-wakatime/packages/wakatime/packages/configparser/__init__.py", line 1131, i
n _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/danzt/.wakatime.cfg'
        [line  5]: 'COMMIT_EDITMSG$\n'
        [line  6]: 'PULLREQ_EDITMSG$\n'
        [line  7]: 'MERGE_MSG$\n'
        [line  8]: 'TAG_EDITMSG$"""\n'
`

**Comment by danzt** [comment]
![errwaka](https://user-images.githubusercontent.com/8420792/133822097-1a8e98ef-754d-41bb-b9e2-c1c668355e27.png)

**Comment by alanhamlett** [comment]
Add a space before the `COMMIT_EDITMSG$` line all the way until `TAG_EDITMSG$` line. Those lines need to be indented.

**Comment by luchaoqi** [comment]
I had a similar problem here and I solved it by removing all wakatime-related files e.g. `rm -rf .wakatime` and reinstalling the plug works for me.
